// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chacal/thread-mgmt-server/pkg/device_gateway (interfaces: DeviceGateway)

// Package mocks is a generated GoMock package.
package mocks

import (
	device_registry "github.com/chacal/thread-mgmt-server/pkg/device_registry"
	gomock "github.com/golang/mock/gomock"
	net "net"
	reflect "reflect"
)

// MockDeviceGateway is a mock of DeviceGateway interface
type MockDeviceGateway struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceGatewayMockRecorder
}

// MockDeviceGatewayMockRecorder is the mock recorder for MockDeviceGateway
type MockDeviceGatewayMockRecorder struct {
	mock *MockDeviceGateway
}

// NewMockDeviceGateway creates a new mock instance
func NewMockDeviceGateway(ctrl *gomock.Controller) *MockDeviceGateway {
	mock := &MockDeviceGateway{ctrl: ctrl}
	mock.recorder = &MockDeviceGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeviceGateway) EXPECT() *MockDeviceGatewayMockRecorder {
	return m.recorder
}

// PushDefaults mocks base method
func (m *MockDeviceGateway) PushDefaults(arg0 device_registry.Defaults, arg1 net.IP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushDefaults", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushDefaults indicates an expected call of PushDefaults
func (mr *MockDeviceGatewayMockRecorder) PushDefaults(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushDefaults", reflect.TypeOf((*MockDeviceGateway)(nil).PushDefaults), arg0, arg1)
}
